require("RSQLite")
surucu <- dbDriver(drvName = "SQLite")
baglanti <- dbConnect(drv = surucu, dbname = "mydb", user = "BK", password = "1234")
ad <- c("Esad Samil", "Osman Alihan", "Seyda", "Cennet", "Melike Ecem")
soyad <- c("GOKTAS", "ONCEL", "URFALIOGLU", "AK", "SERTBAS")
memleket <- c("SIVAS", "BURDUR", "GAZIANTEP", "AMASYA", "ELAZIG")
mail <- c("samo@gmail.com", "oalihan@hotmail.com", "surfalioglu@outlook.com", "cak@yahoo.com", "mecem@ogr.iu.edu.tr")
sektor <- c("Yazilim", "Finans", "Arastirma", "Akademi", "Planlama")
sirket <- c("Peak", "Doktor Takvimi", "Methood", "Istanbul Üniversitesi", "THY")
lakap <- c("CECEN", "OSMEEEN", "GEVEZE", "WHITE", "MECEM")
numara <- c(5415328614, 5381479624, 5067891436, 5544982135, 5384795521)
mydata <- data.frame(ad, soyad, memleket, mail, sektor, sirket, lakap, numara)
dbWriteTable(conn = baglanti, name = "liste", value = mydata)
dbGetQuery(conn = baglanti, statement = "select * from liste order by numara")
dbGetQuery(conn = baglanti, statement = "select * from liste where memleket = 'BURDUR'")
dbGetQuery(conn = baglanti, statement = "select mail from liste where sektor = 'Yazilim'")
dbExecute(conn = baglanti, statement = "insert into liste (ad, soyad, memleket, mail, sektor, sirket, lakap, numara) values('Asena', 'BALLI', 'OSMANIYE', 'ase@gmail.com', 'Hukuk', 'Yavuz Uyanik Hukuk Bürosu', 'Ase', '5418746721')")
dbExecute(conn = baglanti, statement = "delete from liste where memleket ='AMASYA'")
dbGetQuery(conn = baglanti, statement = "select * from liste")